//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference2.HelloWorldResponse HelloWorld(WindowsFormsApplication1.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.HelloWorldResponse> HelloWorldAsync(WindowsFormsApplication1.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modifica", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference2.ModificaResponse Modifica(WindowsFormsApplication1.ServiceReference2.ModificaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modifica", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.ModificaResponse> ModificaAsync(WindowsFormsApplication1.ServiceReference2.ModificaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference2.AgregarResponse Agregar(WindowsFormsApplication1.ServiceReference2.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.AgregarResponse> AgregarAsync(WindowsFormsApplication1.ServiceReference2.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        int Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminarAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApplication1.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApplication1.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modifica", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference2.ModificaRequestBody Body;
        
        public ModificaRequest() {
        }
        
        public ModificaRequest(WindowsFormsApplication1.ServiceReference2.ModificaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        public ModificaRequestBody() {
        }
        
        public ModificaRequestBody(int id, string nombre, string apellido, string direccion) {
            this.id = id;
            this.nombre = nombre;
            this.apellido = apellido;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference2.ModificaResponseBody Body;
        
        public ModificaResponse() {
        }
        
        public ModificaResponse(WindowsFormsApplication1.ServiceReference2.ModificaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ModificaResult;
        
        public ModificaResponseBody() {
        }
        
        public ModificaResponseBody(int ModificaResult) {
            this.ModificaResult = ModificaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Agregar", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference2.AgregarRequestBody Body;
        
        public AgregarRequest() {
        }
        
        public AgregarRequest(WindowsFormsApplication1.ServiceReference2.AgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        public AgregarRequestBody() {
        }
        
        public AgregarRequestBody(string nombre, string apellido, System.DateTime fechaNacimiento, string direccion) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.fechaNacimiento = fechaNacimiento;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference2.AgregarResponseBody Body;
        
        public AgregarResponse() {
        }
        
        public AgregarResponse(WindowsFormsApplication1.ServiceReference2.AgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AgregarResult;
        
        public AgregarResponseBody() {
        }
        
        public AgregarResponseBody(int AgregarResult) {
            this.AgregarResult = AgregarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication1.ServiceReference2.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference2.WebServiceSoap>, WindowsFormsApplication1.ServiceReference2.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference2.HelloWorldResponse WindowsFormsApplication1.ServiceReference2.WebServiceSoap.HelloWorld(WindowsFormsApplication1.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApplication1.ServiceReference2.HelloWorldRequest inValue = new WindowsFormsApplication1.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference2.HelloWorldRequestBody();
            WindowsFormsApplication1.ServiceReference2.HelloWorldResponse retVal = ((WindowsFormsApplication1.ServiceReference2.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.HelloWorldResponse> WindowsFormsApplication1.ServiceReference2.WebServiceSoap.HelloWorldAsync(WindowsFormsApplication1.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApplication1.ServiceReference2.HelloWorldRequest inValue = new WindowsFormsApplication1.ServiceReference2.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference2.HelloWorldRequestBody();
            return ((WindowsFormsApplication1.ServiceReference2.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference2.ModificaResponse WindowsFormsApplication1.ServiceReference2.WebServiceSoap.Modifica(WindowsFormsApplication1.ServiceReference2.ModificaRequest request) {
            return base.Channel.Modifica(request);
        }
        
        public int Modifica(int id, string nombre, string apellido, string direccion) {
            WindowsFormsApplication1.ServiceReference2.ModificaRequest inValue = new WindowsFormsApplication1.ServiceReference2.ModificaRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference2.ModificaRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.direccion = direccion;
            WindowsFormsApplication1.ServiceReference2.ModificaResponse retVal = ((WindowsFormsApplication1.ServiceReference2.WebServiceSoap)(this)).Modifica(inValue);
            return retVal.Body.ModificaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.ModificaResponse> WindowsFormsApplication1.ServiceReference2.WebServiceSoap.ModificaAsync(WindowsFormsApplication1.ServiceReference2.ModificaRequest request) {
            return base.Channel.ModificaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.ModificaResponse> ModificaAsync(int id, string nombre, string apellido, string direccion) {
            WindowsFormsApplication1.ServiceReference2.ModificaRequest inValue = new WindowsFormsApplication1.ServiceReference2.ModificaRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference2.ModificaRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.direccion = direccion;
            return ((WindowsFormsApplication1.ServiceReference2.WebServiceSoap)(this)).ModificaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference2.AgregarResponse WindowsFormsApplication1.ServiceReference2.WebServiceSoap.Agregar(WindowsFormsApplication1.ServiceReference2.AgregarRequest request) {
            return base.Channel.Agregar(request);
        }
        
        public int Agregar(string nombre, string apellido, System.DateTime fechaNacimiento, string direccion) {
            WindowsFormsApplication1.ServiceReference2.AgregarRequest inValue = new WindowsFormsApplication1.ServiceReference2.AgregarRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference2.AgregarRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.direccion = direccion;
            WindowsFormsApplication1.ServiceReference2.AgregarResponse retVal = ((WindowsFormsApplication1.ServiceReference2.WebServiceSoap)(this)).Agregar(inValue);
            return retVal.Body.AgregarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.AgregarResponse> WindowsFormsApplication1.ServiceReference2.WebServiceSoap.AgregarAsync(WindowsFormsApplication1.ServiceReference2.AgregarRequest request) {
            return base.Channel.AgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference2.AgregarResponse> AgregarAsync(string nombre, string apellido, System.DateTime fechaNacimiento, string direccion) {
            WindowsFormsApplication1.ServiceReference2.AgregarRequest inValue = new WindowsFormsApplication1.ServiceReference2.AgregarRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference2.AgregarRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.direccion = direccion;
            return ((WindowsFormsApplication1.ServiceReference2.WebServiceSoap)(this)).AgregarAsync(inValue);
        }
        
        public int Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
